services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: semantic_search_fastapi
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: semantic_search_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    restart: unless-stopped
